### ISSUE TITLE
Copied Glamourer Base 64 string doesn't register as valid

### ISSUE THREAD

**Issue by Aida-Enna** [Ottermandias/Glamourer.Api#1]
I created an "outfit" in Glamourer and copied it to the clipboard and it spit out a base64 string, which correctly validates in a tester. However, when I try to use it in glamourer via the API, it claims it's not a valid base64 string. In the error message, it seems to add an extra character to the string at the start too?

Base 64 string:
"Bh+LCAAAAAAAAAq8V8ty2jAU/RevmYxlya/s8iJJB9IMpMlagQtoImzXkpOhmfx7JRuMJTtupoXuxPW55z59ZN6dIePwCLlgaeKcooFz9bNg2RoS6Zy+O2PKkhuazPX5VsL6Vp0IRigaOBc5CIVZUC5g4JxlGd84pzIvdj+mUvkaFtNj+9zdnjx1/Bg43xeLVjwvJnEQxAj9Q9DK0h3zBqgR0AtjHBwp1nk639ixwmPVpRopjGCBauXBJoexGW4ESyMaIhH2DxbNQ2a0IYA0ouEgONpWXtHcKC32YnysWHcwezGGRgLkHyvYU86ENEqLguOVNhmyZAm51cmjFTf6v+FuaLmQ01X6ZvhWPxTgkYm0ykY8pMslh3k37glopsX4c65SSJKiHNw1p0JAeSxt5RAJIR6JSRC7MYpIy/miEDJds19Qanw6B669VD0TOittj5QX6oBrz7Jy5XkNybxq6RaC7Oy1wj1sMujD3ABbrmQDEbo25ILTpAEI7OdDM1OvFYKyXMgNN/LwcQumEuE6GdHAtZKZvrDkIuXV9HZkxOqrkokNlKiJVZ3flZzNZ4+pmZuNxW5HOxjlQ6CyyAH19d5Aen0tNJC4rz8GknwZ6X8ZGXwZGfYh1RVFZ5sHKmWa9uEqhN11t2Pez3n61rs6u50YwaJ3JRRuuqLGa9PCTNeU81sl2X0B71IBfc+/0be+9RinhVz1bcWIZUKy6o7akXhRB8puX/t9GRdixmGs9KtJ1jENxu3etNI6V5I23SraDuN3ica9UuzmJPCnoAm8qu9irdK9u1eBW/IQtlJ8ApmAUat5A1Uaq4D3NKdrkCq4xtYhfryOCy5ZxpmpwCduS6YbPuqLWlSfSrsaOvDVJB7SpOzfPeQz9QeALj9h17s8Yutnym8TCYlgcmO7dQUpZfEv/LT6XrLFoqgWe6In4p7EHvKDKFDju84B9HV8EoXEd2O1i+fbQiMSun4Uta8xLcBtShK7KA7cqEFJEAoDEu4pceCGEcFeJ2Wt2Ici1Z1WytCg20Nrur3pj3zlCA5JuFXdevu3pKGuz1WXds1ZW3aUtcEumWXtyWDPV31s5ujGZRfVK74j3FvOeLai2tRmv4QZ5Xa2fkzcKPKVZ02PPN8jJGrku7fU9B5GOPS0n/0Gj6l6e9WlpF/gj4/fAAAA//8="

This correctly imports to Glamourer as a lala with the toad head and toad suit (for a silly mod). However, the log shows:

```
07:03:51.959 | ERR | [Glamourer] [DesignConverter] Could not parse base64 string [aBh+LCAAAAAAAAAq8V8ty2jAU/RevmYxlya/s8iJJB9IMpMlagQtoImzXkpOhmfx7JRuMJTtupoXuxPW55z59ZN6dIePwCLlgaeKcooFz9bNg2RoS6Zy+O2PKkhuazPX5VsL6Vp0IRigaOBc5CIVZUC5g4JxlGd84pzIvdj+mUvkaFtNj+9zdnjx1/Bg43xeLVjwvJnEQxAj9Q9DK0h3zBqgR0AtjHBwp1nk639ixwmPVpRopjGCBauXBJoexGW4ESyMaIhH2DxbNQ2a0IYA0ouEgONpWXtHcKC32YnysWHcwezGGRgLkHyvYU86ENEqLguOVNhmyZAm51cmjFTf6v+FuaLmQ01X6ZvhWPxTgkYm0ykY8pMslh3k37glopsX4c65SSJKiHNw1p0JAeSxt5RAJIR6JSRC7MYpIy/miEDJds19Qanw6B669VD0TOittj5QX6oBrz7Jy5XkNybxq6RaC7Oy1wj1sMujD3ABbrmQDEbo25ILTpAEI7OdDM1OvFYKyXMgNN/LwcQumEuE6GdHAtZKZvrDkIuXV9HZkxOqrkokNlKiJVZ3flZzNZ4+pmZuNxW5HOxjlQ6CyyAH19d5Aen0tNJC4rz8GknwZ6X8ZGXwZGfYh1RVFZ5sHKmWa9uEqhN11t2Pez3n61rs6u50YwaJ3JRRuuqLGa9PCTNeU81sl2X0B71IBfc+/0be+9RinhVz1bcWIZUKy6o7akXhRB8puX/t9GRdixmGs9KtJ1jENxu3etNI6V5I23SraDuN3ica9UuzmJPCnoAm8qu9irdK9u1eBW/IQtlJ8ApmAUat5A1Uaq4D3NKdrkCq4xtYhfryOCy5ZxpmpwCduS6YbPuqLWlSfSrsaOvDVJB7SpOzfPeQz9QeALj9h17s8Yutnym8TCYlgcmO7dQUpZfEv/LT6XrLFoqgWe6In4p7EHvKDKFDju84B9HV8EoXEd2O1i+fbQiMSun4Uta8xLcBtShK7KA7cqEFJEAoDEu4pceCGEcFeJ2Wt2Ici1Z1WytCg20Nrur3pj3zlCA5JuFXdevu3pKGuz1WXds1ZW3aUtcEumWXtyWDPV31s5ujGZRfVK74j3FvOeLai2tRmv4QZ5Xa2fkzcKPKVZ02PPN8jJGrku7fU9B5GOPS0n/0Gj6l6e9WlpF/gj4/fAAAA//8=]:
	System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
	   at System.Convert.FromBase64String(String s)
	   at Glamourer.Designs.DesignConverter.FromBase64(String base64, Boolean customize, Boolean equip, Byte& version) in D:\a\Glamourer\Glamourer\Glamourer\Designs\DesignConverter.cs:line 97
```

Code:
```
var GameObjID = gameObj->GetGameObjectId();

string GlamThing = "Bh+LCAAAAAAAAAq8V8ty2jAU/RevmYxlya/s8iJJB9IMpMlagQtoImzXkpOhmfx7JRuMJTtupoXuxPW55z59ZN6dIePwCLlgaeKcooFz9bNg2RoS6Zy+O2PKkhuazPX5VsL6Vp0IRigaOBc5CIVZUC5g4JxlGd84pzIvdj+mUvkaFtNj+9zdnjx1/Bg43xeLVjwvJnEQxAj9Q9DK0h3zBqgR0AtjHBwp1nk639ixwmPVpRopjGCBauXBJoexGW4ESyMaIhH2DxbNQ2a0IYA0ouEgONpWXtHcKC32YnysWHcwezGGRgLkHyvYU86ENEqLguOVNhmyZAm51cmjFTf6v+FuaLmQ01X6ZvhWPxTgkYm0ykY8pMslh3k37glopsX4c65SSJKiHNw1p0JAeSxt5RAJIR6JSRC7MYpIy/miEDJds19Qanw6B669VD0TOittj5QX6oBrz7Jy5XkNybxq6RaC7Oy1wj1sMujD3ABbrmQDEbo25ILTpAEI7OdDM1OvFYKyXMgNN/LwcQumEuE6GdHAtZKZvrDkIuXV9HZkxOqrkokNlKiJVZ3flZzNZ4+pmZuNxW5HOxjlQ6CyyAH19d5Aen0tNJC4rz8GknwZ6X8ZGXwZGfYh1RVFZ5sHKmWa9uEqhN11t2Pez3n61rs6u50YwaJ3JRRuuqLGa9PCTNeU81sl2X0B71IBfc+/0be+9RinhVz1bcWIZUKy6o7akXhRB8puX/t9GRdixmGs9KtJ1jENxu3etNI6V5I23SraDuN3ica9UuzmJPCnoAm8qu9irdK9u1eBW/IQtlJ8ApmAUat5A1Uaq4D3NKdrkCq4xtYhfryOCy5ZxpmpwCduS6YbPuqLWlSfSrsaOvDVJB7SpOzfPeQz9QeALj9h17s8Yutnym8TCYlgcmO7dQUpZfEv/LT6XrLFoqgWe6In4p7EHvKDKFDju84B9HV8EoXEd2O1i+fbQiMSun4Uta8xLcBtShK7KA7cqEFJEAoDEu4pceCGEcFeJ2Wt2Ici1Z1WytCg20Nrur3pj3zlCA5JuFXdevu3pKGuz1WXds1ZW3aUtcEumWXtyWDPV31s5ujGZRfVK74j3FvOeLai2tRmv4QZ5Xa2fkzcKPKVZ02PPN8jJGrku7fU9B5GOPS0n/0Gj6l6e9WlpF/gj4/fAAAA//8=";

Plugin.GlamourerApi.ApplyOutfit((ushort)GameObjID, GlamThing);
```

**Comment by Ottermandias** [comment]
What are you actually calling here? ApplyOutfit or a function with that signature doesn't exist in the API.

**Comment by Ottermandias** [comment]
Well you just made me notice that the apply flags are the wrong way around at least, lol.

But it also works fine for me?

**Comment by Ottermandias** [comment]
`var GameObjID = gameObj->GetGameObjectId();`
this should be the index, not the ID, but that shouldn't be the issue.

**Comment by Ottermandias** [comment]
What is your full log around this? Preferably on verbose. Glamourer should also log the IPC call itself.

**Comment by Ottermandias** [comment]
Eh na?
